FROM node:18

ARG NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN}
ENV NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN}

ARG NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
ENV NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}

ARG NEXT_PUBLIC_PAYLOAD_SCHEMA=${NEXT_PUBLIC_PAYLOAD_SCHEMA}
ENV NEXT_PUBLIC_PAYLOAD_SCHEMA=${NEXT_PUBLIC_PAYLOAD_SCHEMA}

ARG PAYLOAD_API_KEY=${PAYLOAD_API_KEY}
ENV PAYLOAD_API_KEY=${PAYLOAD_API_KEY}


WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3

COPY package.json yarn.lock ./

COPY next.config.js ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

CMD ["yarn", "start"]