import { GetStaticProps } from 'next';
import Head from 'next/head';
import { FC } from 'react';

import { HEADER_QUERY } from '@/api/graphqlQueries';
import { Button, Header_MenuItems } from '@/api/graphqlTypes';
import OutdoorTents from '@/assets/outdoor_tents.jpg';
import Image from '@/atoms/Image/Image';
import Header from '@/components/Header/Header';
import { getData } from '@/utils/getData';

interface HomeProps {
    menuItems: Header_MenuItems[] | null;
    callToAction: Button | null;
}

export const getStaticProps: GetStaticProps = async () => {
    const data = await getData(HEADER_QUERY);

    const { Header: HeaderData } = data || {};

    console.log('data', data);

    return {
        props: {
            menuItems: HeaderData?.menuItems || null,
            callToAction: HeaderData?.callToAction || null
        }
    };
};

const Home: FC<HomeProps> = ({ menuItems, callToAction }) => {
    console.log(callToAction);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Header menuItems={menuItems} callToAction={callToAction} />
            <div style={{ maxWidth: '590px' }}>
                <Image
                    src={OutdoorTents}
                    alt='Outdoor Tents'
                    hasBorder
                    priority
                />
            </div>
            {/* {menuItems?.map((menuItem) => (
        <p key={page?.id}>{page?.title}</p>
      ))} */}
        </>
    );
};

export default Home;
