name: Jest Coverage Report
on:
    pull_request:
        branches: "main"

permissions:
    checks: write
    pull-requests: write

jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              run: yarn install

            - name: Run tests and generate report
              continue-on-error: true
              run: yarn jest --json --outputFile=jest-results.json

            - name: Process test results
              if: success() || failure()
              uses: im-open/process-jest-test-results@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  results-file: "jest-results.json"

            - name: Generate coverage report
              run: |
                  yarn jest --coverage --ci | tee ./coverage.txt && exit ${PIPESTATUS[0]}

            - name: Comment results on PR
              uses: MishaKav/jest-coverage-comment@main
              with:
                  coverage-path: ./coverage.txt
                  coverage-path-prefix: src/
