name: Visual Regression Testing
on:
    pull_request:
        branches: "main"

permissions:
    pages: write
    contents: write
    pull-requests: write

jobs:
    vis_reg_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup node from node version file
              uses: actions/setup-node@v3
              with:
                  node-version: "16"

            - name: Install reg-cli
              run: yarn global add reg-cli

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Generate report with Loki and reg-cli
              run: yarn loki:ci

            - name: Deploy to GitHub Pages
              if: success()
              uses: crazy-max/ghaction-github-pages@v3
              with:
                  build_dir: .loki/report
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
