name: Visual Regression Testing
on:
    pull_request:
        branches: "main"

permissions:
    pages: write
    contents: write
    pull-requests: write

jobs:
    vis_reg_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup node from node version file
              uses: actions/setup-node@v3
              with:
                  node-version: "16"

            - name: Install reg-cli
              run: yarn global add reg-cli

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Generate report with Loki and reg-cli
              run: yarn loki:ci

            - name: Create report folder
              run: |
                  mkdir report
                  mv ./index.html ./.loki ./report
                  mv /current ./.loki ./report
                  mv /diff ./.loki ./report
                  mv /difference ./.loki ./report
                  mv /reference ./.loki ./report

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              if: always()
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./report
                  publish_branch: vrt-report
